version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
